---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-hello-world
spec:
  selector:
    matchLabels:
      app: laravel-hello-world
  template:
    metadata:
      labels:
        app: laravel-hello-world
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: laravel-hello-world
          image: registry.gitlab.com/laravel/lavarel-hello-world:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-hello-world-svc
spec:
  type: ClusterIP
  selector:
    app: laravel-hello-world
  ports:
    - port: 8000
      targetPort: 8000
      name: laravel-hello-world-http
