apiVersion: v1
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.gitlab.com": {
          "auth": "Z2l0bGFiK2RlcGxveS10b2tlbi0xOTIzMTA2OmJSYzZtX05RckJRUDR2NFVVaGZ6"
        }
      }
    }
kind: Secret
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson
